///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class LoginModelData {
/*
{
  "user": 4,
  "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiMDhmYjEzNTA3ZTM4ZmFjNDBiNmI4ODlkNTQzMzc1MGQ4ODNiYmM5MzI3OWQzNjM0NDdkOTNhYzc1MWVkNTg1Nzc4M2IyNDZiMDA5MWU5M2IiLCJpYXQiOjE3MTQ0ODM1OTcuODYzMzE1LCJuYmYiOjE3MTQ0ODM1OTcuODYzMzE4LCJleHAiOjE3NDYwMTk1OTcuODU5NDcyLCJzdWIiOiI0Iiwic2NvcGVzIjpbXX0.WvtXmmjRHmBuMVbclc_DSbX-jx6yDfrD8ob89AhxvYK5tid9jEZzGjLH3W6-e8zhZhRatCy3rdgCW3acvlJi2Uu_pym2D1uHMoQVk2U9sFGP7CCDVuO1DxjerkPZRkCY_OnQ0JObVc0xBPBw_ZQ4vNbnbkG5ZgGq386cUJWx9eTe5kB6XH8z8hbqohBLSNTnAgvQuvCUDXvJUm5v-WRFV_Uh2qFP2xdDGA5HDDJdKMnttjvPqUYemtSQJFpmEnLfaKJCxMLNTTjTWLu9HboV4ib4P4qNGaDp1Z7TghtUb7TuSAl6uTlay8M3kDi9SYDRJL6actHErFVn598uzVBCpbGNFVibOJdk3sCHd59MEQC-kHcdziysRE3XMOVj1QOmXuqTPYHpX0xu8opG0mujaHsbV-Kk42atalLKQbnngNRV3QonBwIhgiEvUgFz-VhyR2dLrObvA7P99QYh2qzja83FYvfyNK28nfp1_thz1p4r8O4Yc55N9IJjcRCpCddsd6z-ZdNyfINzKIgDy8MWNjVjN99xJAwszIML037GuI3S1KpH7vXImwXvhaohO30Yk4hvAcUB9hZ-smsbt0kVBymTA1pxzH4n7RR_OrmgcLW1zwK5cenWla2FJSyd5bfHrF2GT0aw6d1jlTBg0QK3XQEq5DuwMH3m98fXJVDtf2E",
  "noti": true
} 
*/

  int? user;
  String? token;
  bool? noti;

  LoginModelData({
    this.user,
    this.token,
    this.noti,
  });
  LoginModelData.fromJson(Map<String, dynamic> json) {
    user = json['user']?.toInt();
    token = json['token']?.toString();
    noti = json['noti'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['user'] = user;
    data['token'] = token;
    data['noti'] = noti;
    return data;
  }
}

class LoginModel {
/*
{
  "success": true,
  "data": {
    "user": 4,
    "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiMDhmYjEzNTA3ZTM4ZmFjNDBiNmI4ODlkNTQzMzc1MGQ4ODNiYmM5MzI3OWQzNjM0NDdkOTNhYzc1MWVkNTg1Nzc4M2IyNDZiMDA5MWU5M2IiLCJpYXQiOjE3MTQ0ODM1OTcuODYzMzE1LCJuYmYiOjE3MTQ0ODM1OTcuODYzMzE4LCJleHAiOjE3NDYwMTk1OTcuODU5NDcyLCJzdWIiOiI0Iiwic2NvcGVzIjpbXX0.WvtXmmjRHmBuMVbclc_DSbX-jx6yDfrD8ob89AhxvYK5tid9jEZzGjLH3W6-e8zhZhRatCy3rdgCW3acvlJi2Uu_pym2D1uHMoQVk2U9sFGP7CCDVuO1DxjerkPZRkCY_OnQ0JObVc0xBPBw_ZQ4vNbnbkG5ZgGq386cUJWx9eTe5kB6XH8z8hbqohBLSNTnAgvQuvCUDXvJUm5v-WRFV_Uh2qFP2xdDGA5HDDJdKMnttjvPqUYemtSQJFpmEnLfaKJCxMLNTTjTWLu9HboV4ib4P4qNGaDp1Z7TghtUb7TuSAl6uTlay8M3kDi9SYDRJL6actHErFVn598uzVBCpbGNFVibOJdk3sCHd59MEQC-kHcdziysRE3XMOVj1QOmXuqTPYHpX0xu8opG0mujaHsbV-Kk42atalLKQbnngNRV3QonBwIhgiEvUgFz-VhyR2dLrObvA7P99QYh2qzja83FYvfyNK28nfp1_thz1p4r8O4Yc55N9IJjcRCpCddsd6z-ZdNyfINzKIgDy8MWNjVjN99xJAwszIML037GuI3S1KpH7vXImwXvhaohO30Yk4hvAcUB9hZ-smsbt0kVBymTA1pxzH4n7RR_OrmgcLW1zwK5cenWla2FJSyd5bfHrF2GT0aw6d1jlTBg0QK3XQEq5DuwMH3m98fXJVDtf2E",
    "noti": true
  },
  "message": "Login successfully."
} 
*/

  bool? success;
  LoginModelData? data;
  String? message;

  LoginModel({
    this.success,
    this.data,
    this.message,
  });
  LoginModel.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    data = (json['data'] != null) ? LoginModelData.fromJson(json['data']) : null;
    message = json['message']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    data['message'] = message;
    return data;
  }
}
